dateModified: 1649847623
email:
  fromEmail: billy@billymedia.co.uk
  fromName: 'CRAFT STARTER'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3dcc8a9c-1af6-4cb7-b4f3-9102d6f5f013: 'Craft Starter' # Craft Starter
    5175a4de-61e4-46da-a275-8d5e41e17cb6: $SITE_NAME # $SITE_NAME
    312035b6-2af8-4bfe-9cfe-748d42eca72c: Common # Common
    dffe53c7-a4df-4159-9151-9f3d13435b73: 'CRAFT STARTER' # CRAFT STARTER
    f2827411-db98-44a0-9a14-a4c5857ca03d: 'CRAFT STARTER' # CRAFT STARTER
system:
  edition: solo
  live: true
  name: 'CRAFT STARTER'
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
